apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: csm-storage-service
  name: csm-storage-sa
  namespace: huawei-csm

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topo-service-role
  labels:
    app: csm-storage-service
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets", "events", "configmaps" ]
    verbs: [ "create", "get", "update", "delete" ]
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "create", "get", "update", "delete" ]
  - apiGroups: [ "xuanwu.huawei.io" ]
    resources: [ "resourcetopologies", "resourcetopologies/status" ]
    verbs: [ "create", "get", "list", "watch", "update", "delete" ]
  - apiGroups: [ "*" ]
    resources: [ "*" ]
    verbs: [ "get", "list", "watch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cmi-controller-role
  labels:
    app: csm-storage-service
rules:
  - apiGroups: [ "xuanwu.huawei.io" ]
    resources: [ "storagebackendclaims" ]
    verbs: [ "get" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "create", "get", "update" ]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: topo-service-binding
  labels:
    app: csm-storage-service
subjects:
  - kind: ServiceAccount
    name: csm-storage-sa
    namespace: huawei-csm
roleRef:
  kind: ClusterRole
  name: topo-service-role
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cmi-controller-binding
  labels:
    app: csm-storage-service
subjects:
  - kind: ServiceAccount
    name: csm-storage-sa
    namespace: huawei-csm
roleRef:
  kind: ClusterRole
  name: cmi-controller-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: csm-storage-service
  name: csm-storage-service
  namespace: huawei-csm
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: csm-storage-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: csm-storage-service
    spec:
# uncomment if you wish to configure selection constraints for csm-storage-service pods
#      nodeSelector:
#        kubernetes.io/hostname: ""
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - csm-prometheus-service
                topologyKey: kubernetes.io/hostname
              weight: 100
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 15
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 15
      serviceAccount: csm-storage-sa
      serviceAccountName: csm-storage-sa
      containers:
        - name: liveness-probe
          args:
            - --cmi-address=/cmi/cmi.sock
            - --ip-address=[$(POD_IP)]
            - --healthz-port=9808
            - --log-file-dir=/var/log/huawei-csm/csm-storage-service
            - --log-file=liveness-prob
            - --logging-module=file
            - --log-level=info
            - --log-file-size=20M
            - --max-backups=9
          image: csm-liveness-probe:{{version}}
          imagePullPolicy: IfNotPresent
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - mountPath: /cmi
              name: socket-dir
            - mountPath: /var/log
              name: log
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
        - name: cmi-controller
          image: csm-cmi:{{version}}
          env:
            - name: ENDPOINT
              value: /cmi/cmi.sock
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          imagePullPolicy: IfNotPresent
          args:
            - --cmi-address=$(ENDPOINT)
            - --cmi-name=cmi.huawei.com
            - --page-size=100
            - --backend-namespace=huawei-csi
            - --log-file-dir=/var/log/huawei-csm/csm-storage-service
            - --log-file=cmi-service
            - --logging-module=file
            - --log-level=info
            - --log-file-size=20M
            - --max-backups=9
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 3
          ports:
            - containerPort: 9808
              name: healthz
              protocol: TCP
          volumeMounts:
            - mountPath: /cmi
              name: socket-dir
            - mountPath: /var/log/
              name: log
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi
        - args:
            - --cmi-address=$(ENDPOINT)
            - --rt-retry-base-delay=5s
            - --pv-retry-base-delay=5s
            - --pod-retry-base-delay=5s
            - --rt-retry-max-delay=5m
            - --pv-retry-max-delay=1m
            - --pod-retry-max-delay=1m
            - --resync-period=15m
            - --csi-driver-name=csi.huawei.com
            - --backend-namespace=huawei-csi
            - --enable-leader-election=false
            - --leader-lease-duration=8s
            - --leader-renew-deadline=6s
            - --leader-retry-period=2s
            - --log-file-dir=/var/log/huawei-csm/csm-storage-service
            - --log-file=topo-service
            - --logging-module=file
            - --log-level=info
            - --log-file-size=20M
            - --max-backups=9
          env:
            - name: ENDPOINT
              value: /cmi/cmi.sock
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: CLUSTER_NAME
              value: kubernetes
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: csm-topo-service:{{version}}
          imagePullPolicy: IfNotPresent
          name: topo-service
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /cmi
              name: socket-dir
            - mountPath: /var/log
              name: log
            - mountPath: /etc/localtime
              name: host-time
      volumes:
        - emptyDir: { }
          name: socket-dir
        - hostPath:
            path: /var/log/
            type: Directory
          name: log
        - hostPath:
            path: /etc/localtime
            type: File
          name: host-time