{
 "title": "OceanStor",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "StorageName",
    "label": "Storage Device",
    "query": {
     "query": "label_values(huawei_storage_storagepool_used_capacity{endpoint=~\".*\"},endpoint)"
    }
   },
   {
    "name": "ControllerName",
    "label": "Controller",
    "query": {
     "query": "label_values(huawei_storage_controller_total_iops{endpoint=~\"$StorageName\",name=~\".*\"},name)"
    }
   },
   {
    "name": "Pool",
    "label": "Pool",
    "query": {
     "query": "label_values(huawei_storage_storagepool_total_iops{endpoint=~\"$StorageName\",name=~\".*\"},name)"
    }
   },
   { "name": "LunNum", "label": "Lun displayed quantity top", "query": "1,2,3,4,5,6,7,8,9,10" },
   {
    "name": "FileSystemNum",
    "label": "File system displayed quantity top",
    "query": "1,2,3,4,5,6,7,8,9,10"
   },
   {
    "name": "LunName",
    "label": "Lun",
    "query": {
     "query": "label_values(huawei_storage_lun_total_iops{endpoint=~\"$StorageName\",name=~\".*\"},name)"
    }
   },
   {
    "name": "FileSystemName",
    "label": "FileSystem",
    "query": {
     "query": "label_values(huawei_storage_filesystem_capacity_usage{endpoint=~\"$StorageName\",name=~\".*\"},name)"
    }
   },
   {
    "name": "PVName",
    "label": "pv",
    "query": {
     "query": "label_values(huawei_storage_pv_capacity{backend=~\"$StorageName\",pv_name=~\".*\"},pv_name)"
    }
   },
   {
    "name": "VstoreStorageName",
    "label": "Vstore Storage Device",
    "query": {
     "query": "label_values(huawei_storage_vstore_used_capacity{endpoint=~\".*\"},endpoint)"
    }
   },
   {
    "name": "VstoreName",
    "label": "Vstore",
    "query": {
     "query": "label_values(huawei_storage_vstore_free_capacity{endpoint=~\"$VstoreStorageName\", name=~\".*\"},name)"
    }
   },
   {
    "name": "VstorePoolName",
    "label": "Vstore Pool",
    "query": {
     "query": "label_values(huawei_storage_vstore_free_capacity{endpoint=~\"$VstoreStorageName\", pool=~\".*\"},pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "StorageDevice",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
     "options": {
      "content": "<img style=\"display: block;-webkit-user-select: none;margin: auto;cursor: zoom-out;background-color: hsl(0, 0%, 90%);transition: background-color 300ms;\" src=\"https://avatars.githubusercontent.com/u/20315766?s=200&v=4\" width=\"100%\" height=\"100%\">"
     }
    },
    {
     "title": "$StorageName Device Information",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 3, "y": 1 },
     "targets": [
      {
       "expr": "huawei_storage_array_basic_info{endpoint=~\"$StorageName\"}"
      }
     ]
    },
    {
     "title": "$StorageName  Device status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "huawei_storage_array_health_status{endpoint=~\"$StorageName\"}",
       "legendFormat": "Health Status"
      },
      {
       "expr": "huawei_storage_array_running_status{endpoint=~\"$StorageName\"}",
       "legendFormat": "Running Status"
      }
     ]
    },
    {
     "title": "$ControllerName  Controller Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "huawei_storage_controller_health_status{endpoint=~\"$StorageName\", name=~\"$ControllerName\"}",
       "legendFormat": "Health Status"
      },
      {
       "expr": "huawei_storage_controller_running_status{endpoint=~\"$StorageName\", name=~\"$ControllerName\"}",
       "legendFormat": "Running Status"
      }
     ]
    },
    {
     "title": "Total I/Os of controller $ControllerName",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "huawei_storage_controller_total_iops{endpoint=~\"$StorageName\", name=~\"$ControllerName\"}"
      }
     ]
    },
    {
     "title": "Total bandwidth rate of controller $ControllerName",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "huawei_storage_controller_total_bandwidth{endpoint=~\"$StorageName\", name=~\"$ControllerName\"}"
      }
     ]
    },
    {
     "title": "Average I/O response time of controller $ControllerName",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "huawei_storage_controller_avg_io_response_time{endpoint=~\"$StorageName\", name=~\"$ControllerName\"}"
      }
     ]
    },
    {
     "title": "Resource usage of controller $ControllerName",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 6, "x": 9, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "huawei_storage_controller_memory_usage{endpoint=~\"$StorageName\", name=~\"$ControllerName\"}",
       "legendFormat": "Memory usage"
      },
      {
       "expr": "huawei_storage_controller_cpu_usage{endpoint=~\"$StorageName\", name=~\"$ControllerName\"}",
       "legendFormat": "CPU usage"
      }
     ]
    },
    {
     "title": "Total bandwidth rate of storage pool $Pool",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "huawei_storage_storagepool_total_bandwidth{endpoint=~\"$StorageName\", name=~\"$Pool\"}"
      }
     ]
    },
    {
     "title": "Average I/O response time of storage pool $Pool",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "huawei_storage_storagepool_avg_io_response_time{endpoint=~\"$StorageName\", name=~\"$Pool\"}"
      }
     ]
    },
    {
     "title": "Total number of I/Os in storage pool $Pool",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "huawei_storage_storagepool_total_iops{endpoint=~\"$StorageName\", name=~\"$Pool\"}"
      }
     ]
    },
    {
     "title": "Top $FileSystemNum File System Capacity Usage of Storage Pool $Pool ",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(topk($FileSystemNum, huawei_storage_filesystem_capacity_usage{endpoint=~\"$StorageName\", name=~\".*\"}))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Top $LunNum Storage Pool $Pool Lun Capacity Usage Top",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(topk($LunNum, huawei_storage_lun_capacity_usage{endpoint=~\"$StorageName\", name=~\".*\"}))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage of controller $ControllerName",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "huawei_storage_controller_memory_usage{endpoint=~\"$StorageName\", name=~\"$ControllerName\"}",
       "legendFormat": "$ControllerName"
      }
     ]
    },
    {
     "title": "CPU usage of controller $ControllerName",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "huawei_storage_controller_cpu_usage{endpoint=~\"$StorageName\", name=~\"$ControllerName\"}"
      }
     ]
    },
    {
     "title": "Total I/Os of controller $ControllerName",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "huawei_storage_controller_total_iops{endpoint=~\"$StorageName\", name=~\"$ControllerName\"}",
       "legendFormat": "$ControllerName"
      }
     ]
    },
    {
     "title": "Number of read I/Os of controller $ControllerName",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "huawei_storage_controller_read_iops{endpoint=~\"$StorageName\", name=~\"$ControllerName\"}",
       "legendFormat": "$ControllerName"
      }
     ]
    },
    {
     "title": "Number of write I/Os of controller $ControllerName ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "huawei_storage_controller_write_iops{endpoint=~\"$StorageName\", name=~\"$ControllerName\"}",
       "legendFormat": "$ControllerName"
      }
     ]
    },
    {
     "title": "Total bandwidth rate of controller $ControllerName",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "huawei_storage_controller_total_bandwidth{endpoint=~\"$StorageName\", name=~\"$ControllerName\"}",
       "legendFormat": "$ControllerName"
      }
     ]
    },
    {
     "title": "Read bandwidth rate of controller $ControllerName",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "huawei_storage_controller_read_bandwidth{endpoint=~\"$StorageName\", name=~\"$ControllerName\"}",
       "legendFormat": "$ControllerName"
      }
     ]
    },
    {
     "title": "Write bandwidth rate of controller $ControllerName",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "huawei_storage_controller_write_bandwidth{endpoint=~\"$StorageName\", name=~\"$ControllerName\"}",
       "legendFormat": "$ControllerName"
      }
     ]
    },
    {
     "title": "Average I/O response time of controller $ControllerName",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "huawei_storage_controller_avg_io_response_time{endpoint=~\"$StorageName\", name=~\"$ControllerName\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Capacity allocation of storage pool $Pool",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(endpoint) (huawei_storage_lun_capacity{endpoint=~\"$StorageName\", name=~\".*\"})",
       "legendFormat": "Lun"
      },
      {
       "expr": "huawei_storage_storagepool_total_capacity{endpoint=~\"$StorageName\", name=\"$Pool\"} - on(endpoint) sum by(endpoint) (huawei_storage_lun_capacity{endpoint=~\"$StorageName\"}) - sum by(endpoint) (huawei_storage_filesystem_capacity{endpoint=~\"$StorageName\", name=\"$Pool\"})",
       "legendFormat": "Free"
      },
      {
       "expr": "sum by(endpoint) (huawei_storage_filesystem_capacity{endpoint=~\"$StorageName\", name=~\".*\"})",
       "legendFormat": "FileSystem"
      }
     ]
    },
    {
     "title": "Capacity allocation of LUNs in storage pool $Pool",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk($LunNum, huawei_storage_lun_capacity{endpoint=~\"$StorageName\", name=~\".*\"})",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "huawei_storage_storagepool_total_capacity{endpoint=~\"$StorageName\", name=\"$Pool\"} - on(endpoint) sum by(endpoint) (huawei_storage_lun_capacity{endpoint=~\"$StorageName\"})",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Capacity allocation of File System in storage pool $Pool",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk($FileSystemNum, huawei_storage_filesystem_capacity{endpoint=~\"$StorageName\", name=~\".*\"})",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "huawei_storage_storagepool_total_capacity{endpoint=~\"$StorageName\", name=\"$Pool\"} - on(endpoint) sum by(endpoint) (huawei_storage_filesystem_capacity{endpoint=~\"$StorageName\"})",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Capacity usage of storage pool $Pool",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "huawei_storage_storagepool_free_capacity{endpoint=~\"$StorageName\", name=\"$Pool\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "huawei_storage_storagepool_used_capacity{endpoint=~\"$StorageName\", name=\"$Pool\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Total bandwidth rate of storage pool $Pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "huawei_storage_storagepool_total_bandwidth{endpoint=~\"$StorageName\", name=~\"$Pool\"}",
       "legendFormat": "$Pool"
      }
     ]
    },
    {
     "title": "Average I/O response time of storage pool $Pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "huawei_storage_storagepool_avg_io_response_time{endpoint=~\"$StorageName\", name=~\"$Pool\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total number of I/Os in storage pool $Pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "huawei_storage_storagepool_total_iops{endpoint=~\"$StorageName\", name=~\"$Pool\"}",
       "legendFormat": "$Pool"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "Lun",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Capacity usage of LUN $LunName",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "huawei_storage_lun_capacity{endpoint=~\"$StorageName\", name=\"$LunName\"} - (huawei_storage_lun_capacity_usage{endpoint=~\"$StorageName\", name=\"$LunName\"} / 100 * huawei_storage_lun_capacity{endpoint=~\"$StorageName\", name=\"$LunName\"})",
       "legendFormat": "Free"
      },
      {
       "expr": "(huawei_storage_lun_capacity_usage{endpoint=~\"$StorageName\", name=\"$LunName\"} / 100) * huawei_storage_lun_capacity{endpoint=~\"$StorageName\", name=\"$LunName\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Average I/O response time of LUN $LunName",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "huawei_storage_lun_avg_io_response_time{endpoint=~\"$StorageName\", name=~\"$LunName\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total I/O quantity of LUN $LunName",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "huawei_storage_lun_total_iops{endpoint=~\"$StorageName\", name=~\"$LunName\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total bandwidth rate of LUN $LunName",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "huawei_storage_lun_total_bandwidth{endpoint=~\"$StorageName\", name=~\"$LunName\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FileSystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Capacity usage of file system $FileSystemName",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "huawei_storage_filesystem_capacity{endpoint=~\"$StorageName\", name=\"$FileSystemName\"} - (huawei_storage_filesystem_capacity_usage{endpoint=~\"$StorageName\", name=\"$FileSystemName\"} / 100 * huawei_storage_filesystem_capacity{endpoint=~\"$StorageName\", name=\"$FileSystemName\"})",
       "legendFormat": "Free"
      },
      {
       "expr": "(huawei_storage_filesystem_capacity_usage{endpoint=~\"$StorageName\", name=\"$FileSystemName\"} / 100) * huawei_storage_filesystem_capacity{endpoint=~\"$StorageName\", name=\"$FileSystemName\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Total I/O quantity of file system $FileSystemName",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "huawei_storage_filesystem_ops{endpoint=~\"$StorageName\", name=~\"$FileSystemName\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Average read I/O response time of file system $FileSystemName",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "huawei_storage_filesystem_avg_read_ops_response_time{endpoint=~\"$StorageName\", name=~\"$FileSystemName\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Average write I/O response time of file system $FileSystemName",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "huawei_storage_filesystem_avg_write_ops_response_time{endpoint=~\"$StorageName\", name=~\"$FileSystemName\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PV-Lun",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Capacity usage of PV $PVName",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "huawei_storage_pv_capacity{backend=\"$StorageName\",pv_name=\"$PVName\",storage_volume_type=\"oceanstor-san\"} - (huawei_storage_pv_capacity_usage{backend=~\"$StorageName\",pv_name=\"$PVName\",storage_volume_type=\"oceanstor-san\"} / 100 * huawei_storage_pv_capacity{backend=~\"$StorageName\",pv_name=\"$PVName\",storage_volume_type=\"oceanstor-san\"})",
       "legendFormat": "Free"
      },
      {
       "expr": "(huawei_storage_pv_capacity_usage{backend=~\"$StorageName\", pv_name=\"$PVName\",storage_volume_type=\"oceanstor-san\"} / 100) * huawei_storage_pv_capacity{backend=~\"$StorageName\", pv_name=\"$PVName\",storage_volume_type=\"oceanstor-san\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Total I/O quantity of file system $FileSystemName",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "huawei_storage_pv_lun_pv_lun_total_iops{backend=~\"$StorageName\",pv_name=~\"$PVName\"}",
       "legendFormat": "{{pv_name}}"
      }
     ]
    },
    {
     "title": "Average I/O response time of PV $PVName",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "huawei_storage_pv_lun_avg_io_response_time{backend=~\"$StorageName\",pv_name=~\"$PVName\"}",
       "legendFormat": "{{pv_name}}"
      }
     ]
    },
    {
     "title": "Total bandwidth rate of PV $PVName",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "huawei_storage_pv_lun_total_bandwidth{backend=~\"$StorageName\",pv_name=~\"$PVName\"}",
       "legendFormat": "{{pv_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PV-FIleSystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Capacity usage of PV $PVName",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "huawei_storage_pv_capacity{backend=\"$StorageName\",pv_name=\"$PVName\",storage_volume_type=\"oceanstor-nas\"} - (huawei_storage_pv_capacity_usage{backend=~\"$StorageName\",pv_name=\"$PVName\",storage_volume_type=\"oceanstor-nas\"} / 100 * huawei_storage_pv_capacity{backend=~\"$StorageName\",pv_name=\"$PVName\",storage_volume_type=\"oceanstor-nas\"})",
       "legendFormat": "Free"
      },
      {
       "expr": "(huawei_storage_pv_capacity_usage{backend=~\"$StorageName\", pv_name=\"$PVName\",storage_volume_type=\"oceanstor-nas\"} / 100) * huawei_storage_pv_capacity{backend=~\"$StorageName\", pv_name=\"$PVName\",storage_volume_type=\"oceanstor-nas\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Total I/O quantity of PV $PVName",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "huawei_storage_pv_filesystem_ops{backend=~\"$StorageName\",pv_name=~\"$PVName\"}",
       "legendFormat": "{{pv_name}}"
      }
     ]
    },
    {
     "title": "Average read I/O response time of PV $PVName",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "huawei_storage_pv_filesystem_avg_read_ops_response_time{backend=~\"$StorageName\",pv_name=~\"$PVName\"}",
       "legendFormat": "{{pv_name}}"
      }
     ]
    },
    {
     "title": "Average write I/O response time of PV $PVName",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "huawei_storage_pv_filesystem_avg_write_ops_response_time{backend=~\"$StorageName\",pv_name=~\"$PVName\"}",
       "legendFormat": "{{pv_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Vstore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Capacity usage of vstore $VstoreName",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "huawei_storage_vstore_free_capacity{name=\"$VstoreName\", endpoint=\"$VstoreStorageName\", pool=\"$VstorePoolName\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "huawei_storage_vstore_used_capacity{name=\"$VstoreName\", endpoint=\"$VstoreStorageName\", pool=\"$VstorePoolName\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  }
 ]
}